[constants]
# 定义常量以保持整洁
common_flags = ['-fprofile-instr-generate', '-fcoverage-mapping']
linker_flags = ['-fprofile-instr-generate']

[binaries]
# 显式指定使用 Clang，确保不会意外调用 GCC
c = 'clang'
cpp = 'clang++'
# 如果您在 meson.build 里写了自定义 target，这里可以预定义工具路径
llvm-cov = 'llvm-cov'
llvm-profdata = 'llvm-profdata'

[built-in options]
# 针对 C 语言的配置
c_args = common_flags
c_link_args = linker_flags

# 针对 C++ 的配置
cpp_args = common_flags
cpp_link_args = linker_flags
